version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wemedia_user
      WORDPRESS_DB_PASSWORD: 'adgasdfasasdfa234523@@.@'
      WORDPRESS_DB_NAME: wemedia_db
      # Tối ưu PHP
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
    volumes:
      # Chỉ mount wp-content (uploads, themes, plugins)
      - ./wemedia/wp-content:/var/www/html/wp-content
      - ./wemedia/sites:/var/www/html/sites
      - ./wemedia/.htaccess:/var/www/html/.htaccess
      - ./wemedia/wp-config.php:/var/www/html/wp-config.php
      # Tạo custom php.ini
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - wpnet
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wemedia_db
      MYSQL_USER: wemedia_user
      MYSQL_PASSWORD: 'adgasdfasasdfa234523@@.@'
      MYSQL_ROOT_PASSWORD: '123123456'
    volumes:
      # Dùng named volume thay vì bind-mount
      - db_data:/var/lib/mysql
      # Tối ưu MySQL
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - wpnet
    # Không expose port ra ngoài
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local

networks:
  wpnet:
    driver: bridge
